-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-04-19 13:18:57 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE S16_Person CASCADE CONSTRAINTS ;

DROP TABLE S16_Department CASCADE CONSTRAINTS ;

DROP TABLE S16_Par_Child CASCADE CONSTRAINTS ;

DROP TABLE S16_Proj_Emp CASCADE CONSTRAINTS ;

DROP TABLE S16_Project CASCADE CONSTRAINTS ;


CREATE TABLE S16_Department
  (
    dept_no   INTEGER NOT NULL ,
    dept_name VARCHAR2 (255)
  ) ;
ALTER TABLE S16_Department ADD CONSTRAINT S16_Department_PK PRIMARY KEY ( dept_no ) ;


CREATE TABLE S16_Par_Child
  (
    parent_child_id       INTEGER NOT NULL ,
    S16_Person_person_id1 INTEGER ,
    S16_Person_person_id  INTEGER
  ) ;
ALTER TABLE S16_Par_Child ADD CONSTRAINT S16_Par_Child_PK PRIMARY KEY ( parent_child_id ) ;


CREATE TABLE S16_Person
  (
    person_id              INTEGER NOT NULL ,
    type                   VARCHAR2 (255) ,
    first_name             VARCHAR2 (255) ,
    last_name              VARCHAR2 (255) ,
    home_address           VARCHAR2 (255) ,
    zipcode                INTEGER ,
    home_phone             INTEGER ,
    us_citizen             CHAR (1) ,
    employee_id            INTEGER ,
    salary                 INTEGER ,
    salary_exception       CHAR (1) ,
    bonus                  INTEGER ,
    is_fired               CHAR (1) ,
    old_salary             INTEGER ,
    S16_Person_person_id1  INTEGER ,
    S16_Person_person_id   INTEGER ,
    S16_Department_dept_no INTEGER
  ) ;
CREATE UNIQUE INDEX S16_Person__IDX ON S16_Person
  (
    S16_Person_person_id1 ASC
  )
  ;
ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_PK PRIMARY KEY ( person_id ) ;


CREATE TABLE S16_Proj_Emp
  (
    cpe_id                 INTEGER NOT NULL ,
    S16_Project_project_no INTEGER ,
    S16_Person_person_id   INTEGER
  ) ;
ALTER TABLE S16_Proj_Emp ADD CONSTRAINT S16_Proj_Emp_PK PRIMARY KEY ( cpe_id ) ;


CREATE TABLE S16_Project
  (
    project_no             INTEGER NOT NULL ,
    type                   VARCHAR2 (255) ,
    project_title          VARCHAR2 (255) ,
    end_date               DATE ,
    project_active         CHAR (1) ,
    est_person_hours       INTEGER ,
    S16_Project_project_no INTEGER ,
    S16_Person_person_id   INTEGER ,
    S16_Department_dept_no INTEGER
  ) ;
ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_PK PRIMARY KEY ( project_no ) ;


ALTER TABLE S16_Par_Child ADD CONSTRAINT S16_Par_Child_S16_Person_FK FOREIGN KEY ( S16_Person_person_id ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Par_Child ADD CONSTRAINT S16_Par_Child_S16_Person_FKv1 FOREIGN KEY ( S16_Person_person_id1 ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_Department_FK FOREIGN KEY ( S16_Department_dept_no ) REFERENCES S16_Department ( dept_no ) ;

ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_Person_FK FOREIGN KEY ( S16_Person_person_id ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_Person_FKv1 FOREIGN KEY ( S16_Person_person_id1 ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Proj_Emp ADD CONSTRAINT S16_Proj_Emp_S16_Person_FK FOREIGN KEY ( S16_Person_person_id ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Proj_Emp ADD CONSTRAINT S16_Proj_Emp_S16_Project_FK FOREIGN KEY ( S16_Project_project_no ) REFERENCES S16_Project ( project_no ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_Department_FK FOREIGN KEY ( S16_Department_dept_no ) REFERENCES S16_Department ( dept_no ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_Person_FK FOREIGN KEY ( S16_Person_person_id ) REFERENCES S16_Person ( person_id ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_Project_FK FOREIGN KEY ( S16_Project_project_no ) REFERENCES S16_Project ( project_no ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
